### ISSUE TITLE
Error "Failed to get all projects" 

### ISSUE THREAD

**Issue by kerim** [wizonesolutions/2do-to-todoist#1]
Thanks for writing this. It is exactly what I needed! But it doesn't seem to work for me. I keep getting the error message "Failed to get all projects." Any idea why that is happening?

**Comment by kerim** [comment]
I see this project was created two years ago. Maybe the API has changed? Are you still maintaining this project?

**Comment by wizonesolutions** [comment]
Oh, I'm sure you've figured out something by now. Yeah, this isn't maintained anymore. I only needed it once.

The API has probably changed. I think it was beta when I was developing against it. The Sync API would have actually been smarter for this tool, but I didn't want to rewrite it by the time I realized the issues with the REST API.
